apiVersion: v1
kind: Service
metadata:
  labels:
    service: kafka
  name: kafka
spec:
  ports:
  - name: client
    port: 9092
    protocol: TCP
  selector:
    service: kafka
    ---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kafka
  template:
    metadata:
      labels:
        service: kafka
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:latest
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: 1
        - name: KAFKA_CFG_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka:9092
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: ALLOW_PLAINTEXT_LISTENER
          value: yes
        - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
          value: true